language: go
go:
- 1.3
- tip
notifications:
  slack:
    rooms:
      - secure: nuCi6+Pd2gSZbbOR74Kq48RBRf/7HmQ109X2H/5PkEmzvTW4rWJSHUmGdWGVaF9CpVdwUFMTiyEn8AZpOKm17LuRm9JOz18hZuQua0H46EnhCecI31+19DxfOqnLnccSpQ96Hu9mtsLHnD0NGpMhGGSP7gYjhrzuzpE2rX3Pv6iA3agyyJkZSK5nrFnAC0QfjdqWD9HktnCv1iqHiyVsYQHge5YWbRKJWhUa9vZUtOosEcODgQLIbZsbW2bW8MmejYj3l3dK8PuEJyxhp6gyOIfajPZUFTDKbFuAxTYTEkTwsZEpqo9T4C4GzSs9WkLdm9BXL6Q9Ou9gw0PuHN30wsznHzbYsQMkn2ElZ9Ga5bDIY+IM/qcEfNJVOPa4fVGXbUbwACEOGYekupySi+c8FrlWx6YQ2WO7e6puEvzx+DiM2Hz7JioyK/TJCKBgt4kzX2vWF1xH5+k1oO6Aj6gfiXMVspIzXez4bVYiltlKeBHqRSWvjy5GPsJUkmoK5dCPrBMLJm+iNMxGQSV9TCovWyaFIpb6J7V13NV84WV8YMH8SEOhMAzPNXErzCVAJCZRhdeIyqwKAMIjA11W1PoUxuNBAGbdQIEPeOZszdDoKft45gL3B6kSgdaQcImvDx48o/fDY4MFgxrvXfrS/3Qz4/7dCyujdoxu+VM4K+v3Fn8=
